version: '3.1'

services:
 
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: amanha27
      POSTGRES_USER: deyllon
      POSTGRES_DB: apigpt
    ports:
      - 5431:5432
    networks:
      - mynet

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - mynet
networks:
  mynet:
    driver: bridge